import type { Composer } from "./types";

export const ComposerMocks: Composer[] = [
  {
    id: 1,
    name: "Макс Рихтер",
    status: 1,
    deleted: false,
    portraitUrl: null,
    biography: "Макс Рихтер — британский композитор-постминималист немецкого происхождения (род. 1966). Классически образованный выпускник Королевской академии музыки, он стал одним из самых влиятельных современных авторов, работая на стыке академической традиции и электронной музыки.",
    analyzedWorks: 18,
    totalIntervals: 188190,
    period: "2002 - настоящее время",
    polyphonyType: "Минималистичный контрапункт",
    unisonsSecondsFreq: 32.7,
    unisonsSecondsStddev: 2.4,
    thirdsFreq: 24.1,
    thirdsStddev: 1.9,
    fourthsFifthsFreq: 18.3,
    fourthsFifthsStddev: 2.1,
    sixthsSeventhsFreq: 12.8,
    sixthsSeventhsStddev: 1.7,
    octavesFreq: 11.1,
    octavesStddev: 1.5,
  },
  {
    id: 2,
    name: "Людвиг Ван Бетховен",
    status: 1,
    deleted: false,
    portraitUrl: null,
    biography: "В первую очередь уебан, а уже потом Великий немецкий композитор, пианист и дирижёр. Последний представитель венской классической школы. ключевая фигура западной классической музыки в период между классицизмом и романтизмом.",
    analyzedWorks: 32,
    totalIntervals: 285430,
    period: "1770-1827",
    polyphonyType: "Классика + контрапункт",
    unisonsSecondsFreq: 28.4,
    unisonsSecondsStddev: 3.2,
    thirdsFreq: 26.8,
    thirdsStddev: 2.8,
    fourthsFifthsFreq: 22.1,
    fourthsFifthsStddev: 2.5,
    sixthsSeventhsFreq: 15.3,
    sixthsSeventhsStddev: 2.1,
    octavesFreq: 7.4,
    octavesStddev: 1.8,
  },
  {
    id: 3,
    name: "Дзё Хисаиси",
    status: 1,
    deleted: false,
    portraitUrl: null,
    biography: "Японский композитор и музыкальный директор. Известен своими саундтреками к аниме-фильмам Хаяо Миядзаки. Сочетает элементы западной классической музыки с японскими традиционными мотивами.",
    analyzedWorks: 24,
    totalIntervals: 215670,
    period: "1981 - настоящее время",
    polyphonyType: "Остинато",
    unisonsSecondsFreq: 30.2,
    unisonsSecondsStddev: 2.1,
    thirdsFreq: 25.6,
    thirdsStddev: 1.9,
    fourthsFifthsFreq: 20.8,
    fourthsFifthsStddev: 2.0,
    sixthsSeventhsFreq: 14.7,
    sixthsSeventhsStddev: 1.6,
    octavesFreq: 8.7,
    octavesStddev: 1.4,
  },
  {
    id: 4,
    name: "Пьер Булез",
    status: 1,
    deleted: false,
    portraitUrl: null,
    biography: "Французский композитор, дирижёр и музыкальный теоретик. Один из лидеров послевоенного авангарда. Разработал технику сериализма и был пионером электронной музыки.",
    analyzedWorks: 16,
    totalIntervals: 172890,
    period: "1925-2016",
    polyphonyType: "Серийный контрапункт",
    unisonsSecondsFreq: 35.8,
    unisonsSecondsStddev: 4.2,
    thirdsFreq: 18.9,
    thirdsStddev: 3.1,
    fourthsFifthsFreq: 16.4,
    fourthsFifthsStddev: 2.8,
    sixthsSeventhsFreq: 19.2,
    sixthsSeventhsStddev: 3.0,
    octavesFreq: 9.7,
    octavesStddev: 2.1,
  },
  {
    id: 5,
    name: "Дюк Эллингтон",
    status: 1,
    deleted: false,
    portraitUrl: null,
    biography: "Американский джазовый композитор, пианист и руководитель оркестра. Один из наиболее влиятельных фигур в истории джаза. Создал уникальный оркестровый звук и написал более 1000 произведений.",
    analyzedWorks: 28,
    totalIntervals: 245320,
    period: "1899-1974",
    polyphonyType: "Джазовая гетерофония",
    unisonsSecondsFreq: 27.6,
    unisonsSecondsStddev: 2.3,
    thirdsFreq: 29.4,
    thirdsStddev: 2.1,
    fourthsFifthsFreq: 19.8,
    fourthsFifthsStddev: 1.9,
    sixthsSeventhsFreq: 16.2,
    sixthsSeventhsStddev: 1.7,
    octavesFreq: 7.0,
    octavesStddev: 1.2,
  },
  {
    id: 6,
    name: "Филип Гласс",
    status: 1,
    deleted: false,
    portraitUrl: null,
    biography: "Американский композитор-минималист. Один из наиболее влиятельных композиторов конца XX - начала XXI века. Известен своими повторяющимися структурами и гипнотическими музыкальными паттернами",
    analyzedWorks: 22,
    totalIntervals: 145320,
    period: "1937 - настоящее время",
    polyphonyType: "Минималистичная гетерофония",
    unisonsSecondsFreq: 33.5,
    unisonsSecondsStddev: 1.8,
    thirdsFreq: 22.3,
    thirdsStddev: 1.6,
    fourthsFifthsFreq: 21.7,
    fourthsFifthsStddev: 1.9,
    sixthsSeventhsFreq: 13.9,
    sixthsSeventhsStddev: 1.7,
    octavesFreq: 8.6,
    octavesStddev: 1.2,
  },
];